### ISSUE TITLE
KDE script not working on a fresh server install

### ISSUE THREAD

**Issue by avaera8775** [TheLinuxITGuy/Rocky-Scripts#1]
It seems like the KDE script isn't working out of the box. 

Is there a repo that needs to be added or key?

`dnf groupinstall "kde plasma workspaces"`  appears to work, but it's a bloated install. 

Editting the script and adding `--skip-broken` flag might be an option as well.

**Comment by TheLinuxITGuy** [comment]
I like the idea of using groupinstalls. Updated the script today. Thank you for the feedback.
